### ISSUE TITLE
Members not recognized after AzureCP installation

### ISSUE THREAD

**Issue by rajalima** [Yvand/AzureCP#110]
Hi,
After installing AzureCP V16 ,when trying to add members in a SharePoint group, getting the message :"Sorry, you are not allowed to share this with external users."
Reset the azureCP configuration and restrated timer and IIS still no luck.

Thanks

**Comment by Yvand** [comment]
Is it when searching a user or validating it?
Can you check if AzureCP throws an error in SP logs, filter on product/area "azurecp"

**Comment by rajalima** [comment]
Azure CP is not throwing any error . It is when we search for the username.

**Comment by Yvand** [comment]
If AzureCP correctly returns the entity you are searching, it looks like the problem comes from SharePoint. The SharePoint logs on the request that causes this error may help you understand the cause

**Comment by ooditj** [comment]
Hi  Team, we need your help, please help us to fix it :

we are getting following cert issue : 


    
An operation failed because the following certificate has validation errors:


Subject Name: CN=graph.microsoft.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
Issuer Name: CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US
Thumbprint: 48B5B869C6B5E00A14121D987DF888410C77B8D4


Errors:


 The root of the certificate chain is not a trusted root authority..






    
An operation failed because the following certificate has validation errors:


Subject Name: CN=graph.microsoft.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
Issuer Name: CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US
Thumbprint: 48B5B869C6B5E00A14121D987DF888410C77B8D4


Errors:


 PartialChain: A certificate chain could not be built to a trusted root authority.
RevocationStatusUnknown: The revocation function was unable to check revocation for the certificate.
OfflineRevocation: The revocation function was unable to check revocation because the revocation server was offline.
.
