### ISSUE TITLE
AzureCP for use with multiple web apps with different tenants each in a single farm

### ISSUE THREAD

**Issue by vargasfe** [Yvand/AzureCP#113]
Yvan,
I have read somewhere that is is possible to have multiple AzureCP instances running on a single farm to serve multiple web apps, each of which has it's own  separate AzureAD tenant.

Can you please explain how to achieve this?

Thanks,

**Comment by Yvand** [comment]
@vargasfe you can associate a claims provider with only 1 SPTrustedIdentityTokenIssuer.
Is your question related to having several SPTrustedIdentityTokenIssuer in a given web app, or a single SPTrustedIdentityTokenIssuer in multiple web apps ?

**Comment by vargasfe** [comment]
I want to have a SP farm with multiple web apps and each web app is connected to its unique SPTrustedIdentityTokenIssuer  (different from the ones used by the other web apps); and each SPTrustedIdentityTokenIssuer associated with its own, unique AzureCP.
Something like this:
Farm1 - WebAPP1 - SPTITI1 - AzureCP1 - AzureTenant1
Farm1 - WebAPP2 - SPTITI2 - AzureCP2 - AzureTenant2
Farm1 - WebAPP3 - SPTITI3 - AzureCP3 - AzureTenant3

**Comment by Yvand** [comment]
This scenario is technically possible, but in practice I don't encourage you to go for something like this unless you really have to,
In fact I think it would be much easier to create 3 farms, each with it own AAD tenant, than going with this scenario,

With that said, you're right that there is a limitation: due to limitations in SharePoint API, AzureCP won't work if you set it with multiple SPTrustedIdentityTokenIssuer.
A possible solution is to create new custom claims providers that use AzureCP as a base class. It approach works fine but:
- It requires strong SharePoint dev skills to do this properly
- Usually I include a sample package with each build to show how to do it, but I just noticed it's missing in v18. I'll include it in v19, which I'll release soon

**Comment by fabrizioleonttd** [comment]
> This scenario is technically possible, but in practice I don't encourage you to go for something like this unless you really have to, In fact I think it would be much easier to create 3 farms, each with it own AAD tenant, than going with this scenario,
> 
> With that said, you're right that there is a limitation: due to limitations in SharePoint API, AzureCP won't work if you set it with multiple SPTrustedIdentityTokenIssuer. A possible solution is to create new custom claims providers that use AzureCP as a base class. It approach works fine but:
> 
> * It requires strong SharePoint dev skills to do this properly
> * Usually I include a sample package with each build to show how to do it, but I just noticed it's missing in v18. I'll include it in v19, which I'll release soon

Where can i find the sample package in order to understand how to create custom claims providers?

**Comment by Yvand** [comment]
@fabrizioleonttd you can find it in [the assets of the releases](https://github.com/Yvand/AzureCP/releases/tag/v21.0.20230703.25).

**Comment by 3ddyZ** [comment]
@Yvand You said the limitation to one SPTrustedIdentityTokenIssuer was due to a limitation in the SharePoint API.
Does that also apply to EntraCP?

The reason I ask is that we're using EntraCP and have a requirement to assign different SharePoint-sites each to its own tenant. I tried this but it would only work on one site at a time (using the unsupported PowerShell snippet to nullify the ClaimsProviderName on the other SPTrustedIdentityTokenIssuer).

Is it still possible to use the solution that was available for AzureCP (namely the AzureCP.Custom solution in AzureCP.Developers.zip)? I tried adapting it to EntraCP but I could get it to work so far.

Any help on this would be greatly appreciated.

**Comment by Yvand** [comment]
@3ddyZ, yes, due to a design limitation in the SharePoint API, no custom claims provider can work correctly if it is set in multiple SPTrustedIdentityTokenIssuer objects

**Comment by 3ddyZ** [comment]
Thanks for the quick answer @Yvand.

I have succeeded in creating a custom solution based on EntraCP by altering the AzureCP.Custom solution and make necessary changes. I have been able to deploy this custom WSP succesfully on my test environment (next to EntraCP.wsp). However, I can't get one crucial thing to work. 

If I use the code snippet to update the ClaimsProviderName to "EntraCP_CustomName", it says that it couldn't find it.
When using the Get-SPClaimProvider command, it does no longer list EntraCP as a claims provider, nor does it show the EntraCP_CustomName. 

I'm not sure what's missing or what to look for.
Any thoughts on this?
Thanks.

**Comment by 3ddyZ** [comment]
I don't know how this situation came to be (the missing EntraCP when using the ClaimsProviderName command), but it resolved itself after uninstalling and installing EntraCP using the automated powershell scripts from the site.

However I have another question. Does it make sense to deploy both EntraCP.wsp and the Custom wsp? Or should deploying the custom WSP (on its own) suffice when using the example from AzureCP.Developers.zip?

**Comment by 3ddyZ** [comment]
After some days of experimenting with it, I managed to deploy EntraCP.wsp and the CustomEntraCP.wsp on the same SharePoint-server without reported errors. I based my custom WSP on the example project of AzureCP as closely as I could.

When I use Get-SPClaimProvider it now reports the custom claims provider.
However, what baffled me was that it had as DisplayName / Description _"EntraCP"_ and not the custom name.
I managed to add a new one using New_SPClaimProvider _"CustomEntraCP"_ and removed the other.
However, after this it just won't let me add ClaimProvider _"EntraCP"_ again, saying:

_New-SPClaimProvider : The definition specifies a claim provider with a name already in use_

Though it is clearly not in use... or is it?

**Comment by Yvand** [comment]
@3ddy I need to test this scenario, I did not do it yet and it is possible there is an issue in the code that needs to be fixed before this can workj.

Regarding the solutions: It is possible to deploy both solutions in the farm, but you need to be mindful about an important factor:
Both solutions use (obviously) the same dependencies (assemblies). The risk will come when you will update one solution, that it will remove and update assemblies while the other solution still needs the previous version. It could be quite a mess
