### ISSUE TITLE
Problem w/ Work Email being populated

### ISSUE THREAD

**Issue by schrockmatthew** [Yvand/AzureCP#129]
Using Azure federation w/ sharepoint 2019 on premise...AzureCP installed an deployed.....User profile sync using the azure trusted provider and users get imported a bit different then when a user logs in:

When a user logs in:
![image](https://user-images.githubusercontent.com/20209171/123688613-3a15ea80-d820-11eb-87d3-91e9a6351937.png)

But the user profile service import imports all attributes but 'Account name' is different and is not using what attributes are stored in the user profile service connection:

![image](https://user-images.githubusercontent.com/20209171/123689019-c0323100-d820-11eb-9a73-aebbec8cba84.png)
![image](https://user-images.githubusercontent.com/20209171/123689137-e2c44a00-d820-11eb-9c53-1af1fc67fce1.png)

AzureCP is configured as follows:

![image](https://user-images.githubusercontent.com/20209171/123689262-06879000-d821-11eb-9fc8-322a6f3058ff.png)

**Comment by Yvand** [comment]
The very 1st time a user is added to a SPSite (and only that time), AzureCP has a chance to set the metadata of the user.
Eventually, those metadata are overwritten by the data from the User Profile Service (after 1h in the worst case).
Between that time, if you identified that the email metadata was not identical, it is because AzureCP and the User Profile Service do not use the same LDAP attribute to set it. From your screenshot, LDAPCP uses the LDAP attribute "mail" of the user.

**Comment by schrockmatthew** [comment]
The enterprise app setup via azure uses UPN which is really their default email. When we configure the user profile sync, using the same trusted identity that azurecp uses, returns all users but the account name display is a bit different. I’m not sure what you mean for azurecp using email, do you mean the people picker?  I’m just trying to figure out how to have the work email from getting stripped out after sync timer job.
________________________________

**Comment by Yvand** [comment]
Ok, so the title of the issue is confusing since it speaks about the email.
Anyway, the mechanism with the display name is exactly the same as for the email.
In your current (default) config AzureCP uses the AAD attribute DisplayName (in previous comment I wrote LDAP by mistake, sorry).
And eventually, this will be replaced by whatever the User Profile Service has (after 1h maximum).

**Comment by schrockmatthew** [comment]
Sorry I wasn't clear, the main problems are the following:

User profile service imports users as i:0e.t|fedname|username (which means UPN)

When a user logs into the site the users are: i:05.t|fedname|username (which means Email)


I need to get the logging in user to match i:0e.t|fedname|username


________________________________

**Comment by Yvand** [comment]
If I understand your explanation correctly, then you need to update your configuration in the User Profile Service, to map the "User Identifier Claim" to the correct profile property (apparently the email).
This has nothing to do with AzureCP, which is not used import in the User Profile Service
