### ISSUE TITLE
Unable to get MD5 checksum for the key file "AzureCP strong name key.pfx"

### ISSUE THREAD

**Issue by moojjoo** [Yvand/AzureCP#23]
Couple of issues.

1. Keys missing
2. Console app, did you not remove that from the project?

![azurecp](https://user-images.githubusercontent.com/6118065/40249877-f415dc8e-5ac3-11e8-8faa-c80f9e7ffc55.png)

**Comment by Yvand** [comment]
1. I removed the private key which signs the assembly on purpose, you can create your own private key and it will compile successfully
2. It's now removed in the new version 12, which is in development in branch [migrate-to-microsoft-graph](https://github.com/Yvand/AzureCP/tree/migrate-to-microsoft-graph)

I strongly recommend that you start from this new branch [migrate-to-microsoft-graph](https://github.com/Yvand/AzureCP/tree/migrate-to-microsoft-graph) instead of the master, as it brings a lot of changes.

**Comment by moojjoo** [comment]
Thank you.
