### ISSUE TITLE
Groups can't get them mapped

### ISSUE THREAD

**Issue by moojjoo** [Yvand/AzureCP#25]
@Yvand can't get AzureCP to pick up Groups:

http://schemas.microsoft.com/ws/2008/06/identity/claims/role UserType None SharePointGroupId User 

Not working - "RED" in the claims mapping

**Comment by Yvand** [comment]
Line is red because AzureCP didn't find the claim type "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" in the SPTrustedIdentityTokenIssuer.
So either you use another claim type for the groups (and you can update the red line with this claim type), or you didn't set any and you need to add it in the SPTrustedIdentityTokenIssuer.
