### ISSUE TITLE
Azure AD authentication failing after installing AzureCP

### ISSUE THREAD

**Issue by SDMcMillan** [Yvand/AzureCP#26]
Hi Yvan,

I am seeing the following behaviour after installing AzureCP.  User account created in Azure AD appear as username_FQDN#EXT#@AzureDomain.onmicrosoft.com for a user with username@FQDN.  This name appears in the picker in SharePoint 2013 and can be used for alerts, etc. (email and other property values are accessible), however, if you try to login with the email address and password, it fails.  If I select, bypass Azure AD lookup, I can use the email address as a value in the picker and can login using the credentials, but the property values are not mapped, so alerts and emails do not work.  Have you seen this behaviour before?

Thanks.

**Comment by Yvand** [comment]
Do you by any chance have 2 users who look like this in your Azure AD:
username1_FQDN#EXT#@AzureDomain.onmicrosoft.com
username1@FQDN

**Comment by Yvand** [comment]
Ah, I think you face the same issue as https://github.com/Yvand/AzureCP/issues/3
Can you please check?

**Comment by SDMcMillan** [comment]
Hi Yvan,

The step outlined by aboredman <https://github.com/aboredman> worked for
the login, we are using mainly Guest access so it should be fine.  We still
have one issue and that is, how do we extract the mapped information, eg.
phone number or email for the user?

Thanks.

**Comment by Yvand** [comment]
Hi @SDMcMillan 
what do you mean exactly? What should be done with the phone number?

**Comment by SDMcMillan** [comment]
The users can access the site now, but the mapped fields are not accessible
to the user profile service in SharePoint, so if I choose the person field
and mobile phone for example, it is blank for SAML users.

**Comment by Yvand** [comment]
A claims provider cannot ("normally") write in the User Profile Application, it can only populate metadata of the entity (user) in the site collection IF the entity is created for the 1st time.
So in AzureCP you can add PickerEntity metadata for the email and the MobilePhone to populate them in the user properties in the site collection, but it will not write them in the user profile because it's not supposed to do this.
To test if this is working fine, create a new site collection to avoid conflict with existing entities (permissions)
