### ISSUE TITLE
Custom domains allowed?

### ISSUE THREAD

**Issue by moojjoo** [Yvand/AzureCP#45]
@Yvand, are custom domains allowed to use this solution?  I am able to add accounts as guest such as @gmail.com, @yahoo.com, @live.com, however custom domains such as @customname.biz or @customname.com are not working.  They get (Sorry, this site hasn't been shared with you) and I have put them in both as individual users to the SharePoint site and in Groups.

I am actually working with Microsoft Premier team and I want to ensure this is something that does not have to do with the CP Azure Web part?  From the ULS logs I am seeing the following:

```[AzureCP] Starting augmentation for user 'username_gmail.com#ext#@tenantname.onmicrosoft.com'.    8fbba99e-4d7f-b005-52f1-ebe6d6efeae7```

AND

```[AzureCP] Starting augmentation for user 'username@customdomain.com'.    c8baa99e-1ded-b005-52f1-e68cd77ed592```

Do you know why this might be happening?  Because the username@customdomain.com cannot access the SharePoint site, but they do appear to be getting through Microsoft Azure Authentication, again it is stating - (Sorry, this site hasn't been shared with you)

**Comment by Yvand** [comment]
@moojjoo Can you be more explicit on what you want to know exactly?
For AzureCP it doesn't matter if you have custom domains or not, it works with both scenarios

**Comment by moojjoo** [comment]
Yvand not a problem, herer are the more details; the ULS logs are showing users with gmail accounts as 'username_gmail.com#ext#@tenantname.onmicrosoft.com' and being passed to the Sharepoint site as 'username_gmail.com#ext#@tenantname.onmicrosoft.com' and getting into the external SharePoint site with no problems.

The 'username@mmwebs.biz' is being sent through AzureCP, but in the site when we are adding the user are found as 'username_mmwebs.biz#ext#@tenantname.onmicrosoft.com' via the address book, thus getting the SharePoint Message "This site has not been Shared with you".  Basically the 'username@mmwebs.biz' does not match 'username_mmweb.biz#ext#@tenantname.onmicrosoft.com'.

See the attached file(s).  Screen shot of the Users and Screen Shot of the logs

**Comment by AussieDavo** [comment]
Hi @Yvand ,
I believe I have the same problem. It seems that there is no consistency in the UPN set within the SAML token presented to SharePoint by the Azure AD Enterprise Application.

I am using AzureCP primarily for Guest account access to my on-prem SharePoint 2016 environment. I am getting a mix of UPN's being presented for Guest users, some in the "username_domain.com#ext#@tenantname.onmicrosoft.com" format and some in the "username@domain.com" format.

Many of these Guest accounts have their own Office 365 tenancies which I believe may be causing the issue. I have not had enough time to fully test all scenarios but believe that if a Guest account has an Office 365 tenancy and also has an Exchange mailbox in Office 365 then the UPN is presented in the "username@domain.com" format within the SAML token. In all other scenarios the UPN is presented in the "username_domain.com#ext#@tenantname.onmicrosoft.com" format within the SAML token.

I have managed to work around this by switching the "User identifier for 'Guest' users" to "Mail" within the AzureCP global configuration and then using PowerShell to add the users Mail UPN to the site collection:
`New-SPUser -UserAlias 'i:0e.t|azuread|username@domain.com' -Web 'https://ourdomain.com/sites/sitecollection/'
`
`Set-SPUser -Identity 'i:0e.t|azuread|username@domain.com'  -Web 'https://ourdomain.com/sites/sitecollection/'  -Group 'Site Visitors'`
After this I then revert the "User identifier for 'Guest' users" setting back to "UserPrincipalName" in the AzureCP global configuration.

After this I now have both permissions set for either UPN:
i:0e.t|azuread|username@domain.com
i:0e.t|azuread|username_domain.com#ext#@tenantname.onmicrosoft.com
This way if the user logs in with either, they will still have the correct permissions set. This is however not ideal as it requires a SharePoint Admin to configure all Guest permissions.

Could I have configured something incorrectly? Or is there a way to make sure all Guest users are consistently authenticated? 



_________________________________________________________________________________
Here is my configuration...

**Azure AD Enterprise App SSO config:**
Name identifier value: user.userprincipalname

Claim Name | Value
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress | user.mail
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname | user.givenname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name | user.userprincipalname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier | user.userprincipalname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname | user.surname

**SharePoint 2016 on-prem config:**

`PS C:\> Get-SPTrustedIdentityTokenIssuer


ProviderUri                   : https://login.microsoftonline.com/GUID/wsfed
ProviderSignOutUri            :
DefaultProviderRealm          : urn:sharepoint:ourdomain.com
ProviderRealms                : {}
ClaimTypes                    : {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name,
                                http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname,
                                http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname}
HasClaimTypeInformation       : True
ClaimTypeInformation          : {name, GivenName, SurName}
ClaimProviderName             : AzureCP
UseWReplyParameter            : False
UseWHomeRealmParameter        : False
GroupClaimType                :
RegisteredIssuerName          :
IdentityClaimTypeInformation  : Microsoft.SharePoint.Administration.Claims.SPTrustedClaimTypeInformation
Description                   : SharePoint secured by Azure AD
SigningCertificate            : [Subject]
                                  CN=Microsoft Azure Federated SSO Certificate

                                [Issuer]
                                  CN=Microsoft Azure Federated SSO Certificate

                                [Serial Number]
                                  SERIALNUMBER

                                [Not Before]
                                  8/10/2018 5:20:18 PM

                                [Not After]
                                  8/10/2021 5:20:17 PM

                                [Thumbprint]
                                  THUMBPRINT

AdditionalSigningCertificates : {}
MetadataEndPoint              :
IsAutomaticallyUpdated        : False
Name                          : AzureAD
TypeName                      : Microsoft.SharePoint.Administration.Claims.SPTrustedLoginProvider
DisplayName                   : AzureAD
Id                            : GUID
Status                        : Online
Parent                        : SPSecurityTokenServiceManager Name=SecurityTokenServiceManager
Version                       : 793337
DeploymentLocked              : False
Properties                    : {}
Farm                          : SPFarm Name=SP2016_Config
UpgradedPersistedProperties   : {}`

**AzureCP Config:**

Global Config = "UserPrincipalName" for both "User identifier for 'Member' users" and "User identifier for 'Guest' users"

`PS C:\> Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
PS C:\> $config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
PS C:\> $config


AzureTenants                : {GUID}
ClaimTypes                  : {, DisplayName, , ...}
AlwaysResolveUserInput      : False
FilterExactMatchOnly        : False
EnableAugmentation          : False
EntityDisplayTextPrefix     :
EnableRetry                 : False
Timeout                     : 4000
Name                        : AzureCPConfig
TypeName                    : azurecp.AzureCPConfig
DisplayName                 : AzureCPConfig
Id                          : GUID
Status                      : Online
Parent                      : SPFarm Name=SP2016_Config
Version                     : 1441799
DeploymentLocked            : False
Properties                  : {}
Farm                        : SPFarm Name=SP2016_Config
UpgradedPersistedProperties : {}



PS C:\> $config.ClaimTypes


DirectoryObjectPropertyForGuestUsers       : UserPrincipalName
DirectoryObjectProperty                    : UserPrincipalName
EntityType                                 : User
ClaimType                                  : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              :
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : DisplayName
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : True
EntityDataKey                              : DisplayName
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : GivenName
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : True
EntityDataKey                              :
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : Surname
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : True
EntityDataKey                              :
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : Mail
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              : Email
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : MobilePhone
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              : MobilePhone
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : JobTitle
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              : Title
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : Department
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              : Department
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : OfficeLocation
EntityType                                 : User
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              : Location
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : Id
EntityType                                 : Group
ClaimType                                  : http://schemas.microsoft.com/ws/2008/06/identity/claims/role
UseMainClaimTypeOfDirectoryObject          : False
EntityDataKey                              :
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : DisplayName
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}

DirectoryObjectProperty                    : DisplayName
EntityType                                 : Group
ClaimType                                  :
UseMainClaimTypeOfDirectoryObject          : True
EntityDataKey                              : DisplayName
ClaimTypeDisplayName                       :
ClaimValueType                             : http://www.w3.org/2001/XMLSchema#string
PrefixToBypassLookup                       :
DirectoryObjectPropertyToShowAsDisplayText : NotSet
FilterExactMatchOnly                       : False
UpgradedPersistedProperties                : {}`

Please let me know if you require any more information.

**Comment by moojjoo** [comment]
@cblomart in the following statement are you saying you have creating a work around?

> To alleviate that we added:
> 
> the possibility to address other tenants
> the possibility to say for which guest accounts should be shown
> a decorelation between guest accounts (if a UPN without "#ext#" does exist for a user hide any other users with the same UPN but with "#ext#")
> This will allow you to set rights correctly in a SharePoint with AzureCP. Naturally the limitation is that you should have contact or access to administration of other tenants because AzureCP needs access to their directory for the feature mentionned.

The guest accounts we are having problems with are not in other tenants myname@mycompany.com  they do not get the #ext# ---  Does not matter if has #ext# because than they could access the SharePoint account.

**Comment by cblomart** [comment]
This was implemented a while ago to demonstrate sharepoint (on permises) integration with azure ad.

For your second remark... maybe I was not clear... or i don’t understand the issue. 

The understanding i have is the if there is no « #ext# » in the upn present in the openid token_id then the account was directly validated via azure ad. Most commonly present with a tenant.

**Comment by Yvand** [comment]
Guys, can you please check and confirm if your issue is correctly described in [this user voice](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/36274663-sign-in-to-sharepoint-2016-with-guest-accounts-is)?
If that is so, in the short term:
- Consider to vote/comment on the entry
- Starting with AzureCP 13, you can choose what attribute to use for Guest account: 
  - By default it uses "mail": it works only with B2B Guest accounts (accounts that exist in another AAD tenant)
  - You can change to UserPrincipalName instead: it will work only with MSA Guest accounts (e.g. Hotmail/Gmail accounts)

In the future, Azure AD team needs to fix this by providing a consistent attribute for all Guest accounts, which should always be the email address. The more votes the user voice has, the quicker we have a chance to get a fix (with a formal status).

**Comment by moojjoo** [comment]
> This was implemented a while ago to demonstrate sharepoint (on permises) integration with azure ad.
> 
> For your second remark... maybe I was not clear... or i don’t understand the issue.
> 
> The understanding i have is the if there is no « #ext# » in the upn present in the openid token_id then the account was directly validated via azure ad. Most commonly present with a tenant.

Either way, we are having issues that are guests from custom domains.  They are missing the #ext#.  They get through to SharePoint, but because the UPN with the #ext# is not in SharePoint users are getting "This site has not been shared with you"

**Comment by cblomart** [comment]
I am not saying that what was implemented is a complete solution.
By adding the tenant of the custom domain you know of you can add access to users directly from their azure ad without the "#ext#" and they get access properly.
The limitation is that you need to have access to the tenant azure ad to enumerate users.

@Yvand is right in saying that the solution lies within the azure ad team.

They should provide either:
- a way to distinguish MSA accounts from the graph api. I say that because on the azure portal on the azure ad users page, you can see the source of the user: https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties#after-invitation-redemption
- seemless usage of attribute: as @Yvand has proposed in the uservoice, attributes should be consistent. Be it mail or upn, the value recieve in the token should match the one in azure ad.

I voted on the [uservoice](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/36274663-sign-in-to-sharepoint-2016-with-guest-accounts-is) as this make much sense but i think that this is practically difficult tothe azure ad team, otherwise they would have done it this way.

Having the "source" attribute in graph api may provide a way to handle MSA account programmatically in AzureCP. Some work from microsoft is still needed there also.

**Comment by Yvand** [comment]
Hi guys, I come back to this old topic as I tested a workaround that works well:

In the enterprise application in Azure AD: set claim types name / NameIdentifier to user.mail (instead of user.userprincipalname), this will fix the inconsistent usage of “#EXT#” for Guest accounts.
For this to work:

- AAD Connect must be configured to sync mail property of AD OnPrem users
- Azure AD cloud users don’t have their property mail set by default, so it must be set explicitly otherwise they won’t be able to sign-in.
- In AzureCP, set the "user identifier" of both Members and Guests to “Mail” in AzureCP global configuration page.

Is this issue still in your radar?

**Comment by moojjoo** [comment]
I know it fixed me Yvand.  Now true Azure AD Guests and Azure AD Tenant to Tenant Guest can access SharePoint without any issue.

**Comment by AussieDavo** [comment]
Hi @Yvand I made this change in my environment last weekend and eventually got it working. I found that the issue was also lying withing my SPTrustedIdentityTokenIssuer SPClaimTypeMapping configuration.

Previously I had configured my SPTrustedIdentityTokenIssuer like this:

`$realm = "urn:sharepoint:URL"`
`$wsfedurl="https://login.microsoftonline.com/GUID/wsfed"`
`$filepath="D:\Temp\latest.cer"`
`$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($filepath)
New-SPTrustedRootAuthority -Name "AzureAD" -Certificate $cert`

`$map = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"`
`$map2 = New-SPClaimTypeMapping -IncomingClaimType
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming`
`$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming`
`$ap = New-SPTrustedIdentityTokenIssuer -Name "AzureAD" -Description "SharePoint secured by Azure AD" -realm $realm -ImportTrustCertificate $cert -ClaimsMappings $map,$map2,$map3 -SignInUrl $wsfedurl -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"`

However after mapping the incoming claim type for emailaddress to the local claim type upn it then started working as expected. Here is what I did to resolve the issue:

`$realm = "urn:sharepoint:URL"`
`$wsfedurl="https://login.microsoftonline.com/GUID/wsfed"`
`$filepath="D:\Temp\latest.cer"`
`$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($filepath)
New-SPTrustedRootAuthority -Name "AzureAD" -Certificate $cert`

`$map = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" -IncomingClaimTypeDisplayName "emailaddress" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"`
`$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming`
`$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming`
`$ap = New-SPTrustedIdentityTokenIssuer -Name "AzureAD" -Description "SharePoint secured by Azure AD" -realm $realm -ImportTrustCertificate $cert -ClaimsMappings $map,$map2,$map3 -SignInUrl $wsfedurl -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"`

The only issue I have now is that when a new user gets added to a SharePoint group the "Work Email" field is not set so the user does not get an email invitation.

I was thinking of adding another SPClaimTypeMapping by adding the following to my script:

`$map1 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" -IncomingClaimTypeDisplayName "emailaddress" -SameAsIncoming`

But not sure if I can use duplicate IncomingClaimType's?

I'm interested to see how others have setup their SPTrustedIdentityTokenIssuer and if there is an easier way to add, remove and change claim type mappings. I'm aware that AzureCP has a Claims Types Config but not sure of the best way to set it up. Does anyone have a screenshot of a working AzureCP Claim Types Config?

Here is a screenshot of my working AzureCP Claim Types Config (apart form the email invitation functionality):

![image](https://user-images.githubusercontent.com/5260349/57340999-d762c000-717b-11e9-8657-e84ba1ba6d22.png)

**Comment by AussieDavo** [comment]
I solved the issue in my previous comment about:

> The only issue I have now is that when a new user gets added to a SharePoint group the "Work Email" field is not set so the user does not get an email invitation.
 
All I needed to do was add the "Email" attribute to the PickerEntity Metadata for my main claim type: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"

Like this: 
![image](https://user-images.githubusercontent.com/5260349/63071242-da7f0080-bf61-11e9-9cb2-ae946893251c.png)


Found in the in the AzureCP Claim types configuration in central admin: http://server_name/_admin/azurecp/ClaimTypesConfig.aspx

Now the email address gets populated as soon as the user is added by people picker. As a result invitation emails are now working for these users too.

**Comment by Yvand** [comment]
@totayo1000 sorry I forgot this issue. Did you manage to edit the entry successfully?
