### ISSUE TITLE
AZURECP :-The table is not keeping the "Email" value, the cell return to empty after clicking on save

### ISSUE THREAD

**Issue by upatel911** [Yvand/AzureCP#84]
Reference to same issue raised by Custom domains allowed?  #45 

Issue found in the in the AzureCP Claim types configuration in central admin: http://server_name/_admin/azurecp/ClaimTypesConfig.aspx
![64766645-05537900-d54f-11e9-8bf0-4087fe8f568e](https://user-images.githubusercontent.com/64625880/80780466-0583a180-8b3d-11ea-8f01-3c22c148ecd8.png)

The issue is that after configuring the AzureCP on SP 2016 On-Premise the email address not gets populated as soon as the user is added by people picker. As a result invitation emails are now working for these users too.

Any solution please.

**Comment by Yvand** [comment]
You changed the default configuration and associated the metadata Email with the Azure AD property UserPrincipalName.
But it should be associated with the Azure AD property Mail instead, as done by default: 
![image](https://user-images.githubusercontent.com/8788631/81049841-47a33f00-8ebf-11ea-8708-34dcdfdc84c4.png)

**Comment by upatel911** [comment]
Hello Yvand,
Thank you so much for your prompt reply and suggestion.
Here below are my configuration settings. can you please review and let me know where i am wrong setting it up. The "Work Email" not saving under Picker Entity.

<img width="490" alt="UserAttributes" src="https://user-images.githubusercontent.com/64625880/81068373-40c00080-8eae-11ea-8b89-b0560123eba0.PNG">

**Comment by upatel911** [comment]
I have sent you the User Attributes screenshot above.
here below are the AZURECP configuration. Please advise where I am wrong here.

![Global Configuration](https://user-images.githubusercontent.com/64625880/81068524-811f7e80-8eae-11ea-83c4-ac0fa3e0055a.png)

![Claim Type Configuration](https://user-images.githubusercontent.com/64625880/81068565-94324e80-8eae-11ea-9358-ec92f8bf07fe.png)

**Comment by Yvand** [comment]
I recommend that you configure Azure AD and the SharePoint trust as documented in [this page](https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial).
In your current configuration, you use the emailaddress claim type as the identity claim type. This is different from the recommended configuration above.

**Comment by upatel911** [comment]
Thank you.
I think the work email issue resolved now.

**Comment by uday30980** [comment]
Thank You Yvand its working. the Work Email issue resolved with new configuration. i have attacheed the new claim type configuration screenshot.
However got the following issues. Need your expert advise to fix this issue.
We have 3 tier farm.
1. Application Server (Running Central Admin Site and Search)
2. WFE1 (load balancing)
3. WFE2 (load balancing)
The People Picker Control not working and not giving any results when request go to WFE1.
The People Picker Control working fine on WFE2 when search for the users.
We have checked the ULS Logs on WFE1 and found the following errors multiple times...

Unexpected	[AzureCP] Cannot continue because identity claim type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn' set in the SPTrustedIdentityTokenIssuer 'AzureAD' is missing in the ClaimTypeConfig list.	69a34f9f-dafc-c0d8-649e-a10bf4e3a569
05/05/2020 23:31:27.32 	w3wp.exe (0x20F0)    	0x25F4	AzureCP                       	Core                          	1337

**Comment by uday30980** [comment]
here below are my existing mapping.....

$map1 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" -IncomingClaimTypeDisplayName "Role" -SameAsIncoming
$ap = New-SPTrustedIdentityTokenIssuer   -Name "AzureAD"  -Description "SharePoint secured by Azure AD"  -realm $realm  -ImportTrustCertificate $cert  -ClaimsMappings $map1,$map2 -SignInUrl $wsfedurl  -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

**Comment by Yvand** [comment]
@uday30980 you just need to reset the AzureCP claim types mapping. You can do that in the central administration > security > AzrueCP claim types mapping page, and click on button Reset configuration.

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
