### ISSUE TITLE
Quick question on AzureCP function

### ISSUE THREAD

**Issue by LachlanJB** [Yvand/AzureCP#98]
Hi,
Is it possible to have the AzureCP work for 2 SharePoint WebApps that each authenticate against their own enterprise app in Azure Active Directory (same Azure Tenancy)?

I see that the documentation specifies that "Due to limitations of SharePoint API, do not associate AzureCP with more than 1 SPTrustedIdentityTokenIssuer" so I assume this will require development of the AzureCP solution to make this possible?

Alternatively, is it more simple to configure the Trusted identity Provider (in Azure AD & SharePoint) to work across both web applications and then continue to use the AzureCP against the 1 SPTrustedIdentityTokenIssuer that is now working on 2 web applications. In this scenario the user security would be assigned at the SharePoint level and not at the AzureAD App level?

The last section of the documentation details this second approach and it looks quite straight forward so I would assume it wouldn't create any issues for AzureCP
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial

Best Regards
Lachlan

**Comment by Yvand** [comment]
Unfortunately, you cannot set AzureCP with 2 SPTrustedIdentityTokenIssuer, that's not something that can be fixed in AzureCP as it's really a SharePoint limitation.
But there is a possible solution: you can associate AzureCP with 1, and use AzureCP.Developers.zip (that comes with each release) to createa a copy of AzureCP and associate it with the 2nd SPTrustedIdentityTokenIssuer. However, this approach requires dev skills in SharePoint and I don't recommend this approach if you're not familiar with it.
